### ISSUE TITLE
tiny typo bug.

### ISSUE THREAD

**Issue by JettMonstersGoBoom** [visrealm/vrEmu6502#5]
line 623 
`      case AddrModeIndY:
        if (addr8Label)
          snprintf(buffer, bufferSize, "(%s, x)", addr8Label);`

should be 
`          snprintf(buffer, bufferSize, "(%s),y", addr8Label);`

not convinced this values a PR.

**Comment by visrealm** [comment]
Thanks, Jett.

 

Fixed.

 

Cheers

Troy

 

From: Jett ***@***.***> 
Sent: Saturday, February 3, 2024 2:07 AM
To: visrealm/vrEmu6502 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [visrealm/vrEmu6502] tiny typo bug. (Issue #5)

 

line 623
case AddrModeIndY: if (addr8Label) snprintf(buffer, bufferSize, "(%s, x)", addr8Label);

should be
snprintf(buffer, bufferSize, "(%s),y", addr8Label);

not convinced this values a PR.

**Comment by visrealm** [comment]
Fixed
